version: '3'

services:

  mysql8:
    container_name: test_mysql8
    restart: always
    build: ./
    ports:
      - '3306'
    volumes:
      - /mnt/users/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=abc123
      - MYSQL_USER=test_user
      - MYSQL_PASSWORD=abc888
    security_opt:
      - seccomp:unconfined  
    networks:
      - mysql_net  

networks:
  mysql_net:
